=== apache/db-jdo/api/src/main/resources/javax/jdo/jdoconfig_3_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<xs:schema
  targetNamespace="https://db.apache.org/jdo/xmlns/jdoconfig"
  xmlns="https://db.apache.org/jdo/xmlns/jdoconfig"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:jdoconfig="https://db.apache.org/jdo/xmlns/jdoconfig"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  version="3.2">
  <xs:annotation>
    <xs:documentation>
      This is the XML Schema for the JDO configuration file.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="jdoconfig">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation>
          The root configuration element for JDO.
        </xs:documentation>
      </xs:annotation>
      <xs:sequence>
        <xs:element name="persistence-manager-factory" minOccurs="1"
              maxOccurs="unbounded">
          <xs:complexType>
            <xs:annotation>
              <xs:documentation>
                Standard JDO PersistenceManagerFactory configuration properties.
                Vendor-specific properties are set using additional 
                vendor-specific attributes and/or property elements.
              </xs:documentation>
            </xs:annotation>
            <xs:sequence minOccurs="0" maxOccurs="1">
              <xs:element name="property" minOccurs="0"
                    maxOccurs="unbounded">
                <xs:complexType>
                  <xs:annotation>
                    <xs:documentation>
                      Vendor-specific properties.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:attributeGroup ref="attlist.property"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="instance-lifecycle-listener"
                    minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:annotation>
                    <xs:documentation>
                      javax.jdo.listener.InstanceLifecycleListener instance 
                      configuration. There is one instance-lifecycle-listener 
                      element per listener instance. Only one instance of the 
                      listener class is supported in this configuration file.
                      If multiple instances of the same listener class is 
                      required, then the API
                      PersistenceManagerFactory.addInstanceLifecycleListener(...)
                      must be used.

                      If attribute "classes" is missing, all persistence-capable
                      instances are observed; otherwise it is a comma- or
                      whitespace-delimited list of persistence-capable
                      classes whose instances will be observed.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:attributeGroup
                    ref="attlist.instance-lifecycle-listener"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attributeGroup
              ref="attlist.persistence-manager-factory"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.jdoconfig"/>
    </xs:complexType>
  </xs:element>

  <xs:attributeGroup name="attlist.jdoconfig"/>

  <xs:attributeGroup name="attlist.persistence-manager-factory">
    <xs:annotation>
      <xs:documentation>
        These are attributes corresponding to the standard properties
        defined in JDO.
        Any other attributes present, if unrecognized by a JDO
        implementation, may be silently ignored.
      </xs:documentation>
    </xs:annotation>

    <!-- Corresponds to standard JDO property javax.jdo.PersistenceManagerFactoryClass. -->
    <xs:attribute name="class" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.Name.
        The absence of this attribute implies the anonymous PMF. -->
    <xs:attribute name="name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.PersistenceUnitName. -->
    <xs:attribute name="persistence-unit-name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.Optimistic. -->
    <xs:attribute name="optimistic" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ReadOnly. -->
    <xs:attribute name="readonly" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.RetainValues. -->
    <xs:attribute name="retain-values" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.RestoreValues. -->
    <xs:attribute name="restore-values" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.IgnoreCache. -->
    <xs:attribute name="ignore-cache" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.NontransactionalRead. -->
    <xs:attribute name="nontransactional-read" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.NontransactionalWrite. -->
    <xs:attribute name="nontransactional-write" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.Multithreaded. -->
    <xs:attribute name="multithreaded" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.TransactionIsolationLevel. -->
    <xs:attribute name="transaction-isolation-level" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionDriverName. -->
    <xs:attribute name="connection-driver-name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionUserName. -->
    <xs:attribute name="connection-user-name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionPassword. -->
    <xs:attribute name="connection-password" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionURL. -->
    <xs:attribute name="connection-url" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionFactoryName. -->
    <xs:attribute name="connection-factory-name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ConnectionFactory2Name. -->
    <xs:attribute name="connection-factory2-name" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.Mapping. -->
    <xs:attribute name="mapping" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.DetachAllOnCommit. -->
    <xs:attribute name="detach-all-on-commit" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.ServerTimeZoneID. -->
    <xs:attribute name="server-time-zone-id" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.DatastoreReadTimeoutMillis. -->
    <xs:attribute name="datastore-read-timeout-millis" use="optional"/>
    <!-- Corresponds to standard JDO property javax.jdo.option.DatastoreWriteTimeoutMillis. -->
    <xs:attribute name="datastore-write-timeout-millis" use="optional"/>
    <!-- Any other vendor-specific attributes are allowed and passed literally 
        to the underlying implementation. -->
    <xs:anyAttribute processContents="lax"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="attlist.property">
    <!-- The name of the vendor-specific property. -->
    <xs:attribute name="name" use="required"/>
    <!-- The value of the vendor-specific property. -->
    <xs:attribute name="value" use="optional"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="attlist.instance-lifecycle-listener">
    <!-- The name of the listener class to instantiate. -->
    <xs:attribute name="listener" use="required"/>
    <!-- Comma- or whitespace-delimited list of persistence-capable classes 
        whose instances to observe.  The absence of this attribute means 
        to observe all. -->
    <xs:attribute name="classes" use="optional"/>
  </xs:attributeGroup>

</xs:schema>

=== apache/db-jdo/api/src/test/resources/jdoconfig/Positive00/META-INF/jdoconfig.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!--
    Do not change any values in this file without also making changes to
    JDOHelperConfigTest.java, as that file depends on the values in this one!
-->
<jdoconfig xmlns="https://db.apache.org/jdo/xmlns/jdoconfig"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://db.apache.org/jdo/xmlns/jdoconfig_3_2.xsd">

    <!--
        Basic PMF config using attributes & listeners with no nonstandard
        properties.
    -->
    <persistence-manager-factory
        class="class.positive00.pmf0"
        connection-driver-name="connection-driver-name.positive00.pmf0"
        connection-factory-name="connection-factory-name.positive00.pmf0"
        connection-factory2-name="connection-factory2-name.positive00.pmf0"
        connection-password="connection-password.positive00.pmf0"
        connection-url="connection-url.positive00.pmf0"
        connection-user-name="connection-user-name.positive00.pmf0"
        ignore-cache="ignore-cache.positive00.pmf0"
        mapping="mapping.positive00.pmf0"
        multithreaded="multithreaded.positive00.pmf0"
        nontransactional-read="nontransactional-read.positive00.pmf0"
        nontransactional-write="nontransactional-write.positive00.pmf0"
        optimistic="optimistic.positive00.pmf0"
        name="name.positive00.pmf0"
        persistence-unit-name="persistence-unit-name.positive00.pmf0"
        restore-values="restore-values.positive00.pmf0"
        retain-values="retain-values.positive00.pmf0"
        detach-all-on-commit="detach-all-on-commit.positive00.pmf0"
        server-time-zone-id="server-time-zone-id.positive00.pmf0">

        <instance-lifecycle-listener
            listener="listener.positive00.pmf0.listener0"
            classes="classes.positive00.pmf0.classes0"
            />
        <instance-lifecycle-listener
            listener="listener.positive00.pmf0.listener1"
            classes="classes.positive00.pmf0.classes1"
            />
    </persistence-manager-factory>

    <!--
        Basic PMF config using only <property> elements with javax.jdo
        properties and no nonstandard properties.
    -->
    <persistence-manager-factory>
        <property
            name="javax.jdo.PersistenceManagerFactoryClass"
            value="class.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionDriverName"
            value="connection-driver-name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionFactoryName"
            value="connection-factory-name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionFactory2Name"
            value="connection-factory2-name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionPassword"
            value="connection-password.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionURL"
            value="connection-url.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ConnectionUserName"
            value="connection-user-name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.IgnoreCache"
            value="ignore-cache.positive00.pmf1"/>
        <property
            name="javax.jdo.option.Mapping"
            value="mapping.positive00.pmf1"/>
        <property
            name="javax.jdo.option.Multithreaded"
            value="multithreaded.positive00.pmf1"/>
        <property
            name="javax.jdo.option.NontransactionalRead"
            value="nontransactional-read.positive00.pmf1"/>
        <property
            name="javax.jdo.option.NontransactionalWrite"
            value="nontransactional-write.positive00.pmf1"/>
        <property
            name="javax.jdo.option.Optimistic"
            value="optimistic.positive00.pmf1"/>
        <property
            name="javax.jdo.option.Name"
            value="name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.PersistenceUnitName"
            value="persistence-unit-name.positive00.pmf1"/>
        <property
            name="javax.jdo.option.DetachAllOnCommit"
            value="detach-all-on-commit.positive00.pmf1"/>
        <property
            name="javax.jdo.option.RestoreValues"
            value="restore-values.positive00.pmf1"/>
        <property
            name="javax.jdo.option.RetainValues"
            value="retain-values.positive00.pmf1"/>
        <property
            name="javax.jdo.option.ServerTimeZoneID"
            value="server-time-zone-id.positive00.pmf1"/>

        <instance-lifecycle-listener
            listener="listener.positive00.pmf1.listener0"
            classes="classes.positive00.pmf1.classes0"
            />
        <instance-lifecycle-listener
            listener="listener.positive00.pmf1.listener1"
            classes="classes.positive00.pmf1.classes1"
            />
    </persistence-manager-factory>

    <!--
        PMF config that uses nested <property> elements with standard
        attribute names instead of javax.jdo property names and no nonstandard
        properties.
    -->
    <persistence-manager-factory>
        <property
            name="class"
            value="class.positive00.pmf2"/>
        <property
            name="connection-driver-name"
            value="connection-driver-name.positive00.pmf2"/>
        <property
            name="connection-factory-name"
            value="connection-factory-name.positive00.pmf2"/>
        <property
            name="connection-factory2-name"
            value="connection-factory2-name.positive00.pmf2"/>
        <property
            name="connection-password"
            value="connection-password.positive00.pmf2"/>
        <property
            name="connection-url"
            value="connection-url.positive00.pmf2"/>
        <property
            name="connection-user-name"
            value="connection-user-name.positive00.pmf2"/>
        <property
            name="ignore-cache"
            value="ignore-cache.positive00.pmf2"/>
        <property
            name="mapping"
            value="mapping.positive00.pmf2"/>
        <property
            name="multithreaded"
            value="multithreaded.positive00.pmf2"/>
        <property
            name="nontransactional-read"
            value="nontransactional-read.positive00.pmf2"/>
        <property
            name="nontransactional-write"
            value="nontransactional-write.positive00.pmf2"/>
        <property
            name="optimistic"
            value="optimistic.positive00.pmf2"/>
        <property
            name="name"
            value="name.positive00.pmf2"/>
        <property
            name="persistence-unit-name"
            value="persistence-unit-name.positive00.pmf2"/>
        <property
            name="detach-all-on-commit"
            value="detach-all-on-commit.positive00.pmf2"/>
        <property
            name="restore-values"
            value="restore-values.positive00.pmf2"/>
        <property
            name="retain-values"
            value="retain-values.positive00.pmf2"/>
        <property
            name="javax.jdo.option.ServerTimeZoneID"
            value="server-time-zone-id.positive00.pmf2"/>

        <instance-lifecycle-listener
            listener="listener.positive00.pmf2.listener0"
            classes="classes.positive00.pmf2.classes0"
            />
        <instance-lifecycle-listener
            listener="listener.positive00.pmf2.listener1"
            classes="classes.positive00.pmf2.classes1"
            />
    </persistence-manager-factory>

    <!--
        PMF config using standard attributes plus nonstandard properties in
        <property> elements.
    -->
    <persistence-manager-factory
        class="class.positive00.pmf3"
        connection-driver-name="connection-driver-name.positive00.pmf3"
        connection-factory-name="connection-factory-name.positive00.pmf3"
        connection-factory2-name="connection-factory2-name.positive00.pmf3"
        connection-password="connection-password.positive00.pmf3"
        connection-url="connection-url.positive00.pmf3"
        connection-user-name="connection-user-name.positive00.pmf3"
        ignore-cache="ignore-cache.positive00.pmf3"
        mapping="mapping.positive00.pmf3"
        multithreaded="multithreaded.positive00.pmf3"
        nontransactional-read="nontransactional-read.positive00.pmf3"
        nontransactional-write="nontransactional-write.positive00.pmf3"
        optimistic="optimistic.positive00.pmf3"
        name="name.positive00.pmf3"
        persistence-unit-name="persistence-unit-name.positive00.pmf3"
        restore-values="restore-values.positive00.pmf3"
        retain-values="retain-values.positive00.pmf3"
        detach-all-on-commit="detach-all-on-commit.positive00.pmf3"
        server-time-zone-id="server-time-zone-id.positive00.pmf3">

        <property name="property.positive00.pmf3.name0"
                  value="property.positive00.pmf3.value0"/>
        <property name="property.positive00.pmf3.name1"
                  value="property.positive00.pmf3.value1"/>
